# Generated by Django 4.1 on 2022-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('position', models.TextField()),
                ('hiring_date', models.DateField()),
            ],
        ),
    ]
