# Generated by Django 4.1 on 2022-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='file',
            field=models.TextField(),
        ),
    ]
