# Generated by Django 4.1 on 2022-08-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_alter_vacationrequest_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationrequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='emp_id',
            field=models.IntegerField(default=-1),
        ),
    ]
