# Generated by Django 4.1 on 2022-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_alter_vacationrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
