# Generated by Django 4.1 on 2022-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
    ]
