# Generated by Django 4.1 on 2022-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationrequest',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='emp_email',
            field=models.EmailField(default=-1, max_length=254),
        ),
    ]
